/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 man.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Man(props) {
  const { nodes, materials } = useGLTF("/models/man.glb");
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Avatar.geometry}
        material={materials.Wolf3D_Avatar}
        skeleton={nodes.Wolf3D_Avatar.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/man.glb");
