/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 woman.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Woman(props) {
  const { nodes, materials } = useGLTF("/models/woman.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Object_3.geometry}
          material={materials["Material.004"]}
          skeleton={nodes.Object_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.004"]}
          skeleton={nodes.Object_4.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/woman.glb");
