/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 curtains.glb
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function Curtain(props) {
  const { nodes, materials } = useGLTF("/models/curtains.glb");

  const bakedTexture = useTexture("/textures/curtains/curtainLeft.jpg");
  const bakedTexture2 = useTexture("/textures/curtains/curtainRight.jpg");
  bakedTexture.flipY = false;
  bakedTexture2.flipY = false;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.curtain01.geometry}
        position={[-8.63, 9.489, -10.797]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.curtain02.geometry}
        material={nodes.curtain02.material}
        position={[9.641, 9.489, -10.797]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture2} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/curtains.glb");
