/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 floor.glb
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function Floors(props) {
  const { nodes, materials } = useGLTF("/models/floor.glb");

  const bakedTexture = useTexture("/textures/floors/floor01.jpg");
  const bakedTexture2 = useTexture("/textures/floors/floor02.jpg");
  const bakedTexture3 = useTexture("/textures/floors/floor03.jpg");

  bakedTexture.encoding = THREE.sRGBEncoding;
  bakedTexture2.encoding = THREE.sRGBEncoding;
  bakedTexture3.encoding = THREE.sRGBEncoding;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor.geometry} position={[3.322, 2.315, 11.576]}>
        <meshBasicMaterial
          map={
            props.floorTexture === "01"
              ? bakedTexture
              : props.floorTexture === "02"
              ? bakedTexture2
              : props.floorTexture === "03"
              ? bakedTexture3
              : null
          }
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/floor.glb");
