/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 test02.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room(props) {
  const { nodes, materials } = useGLTF("/models/room.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0.472, 16.339, -11.063]}
      />
      <mesh
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
        position={[0.135, 12.808, 0.176]}
      />
      <mesh
        geometry={nodes.Wall.geometry}
        material={nodes.Wall.material}
        position={[0.135, 9.745, 0.176]}
      />
      <mesh
        geometry={nodes.Window.geometry}
        material={nodes.Window.material}
        position={[0.135, 14.072, 0.176]}
      />
    </group>
  );
}

useGLTF.preload("/models/room.glb");
