/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 windows.glb
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function WindowBody(props) {
  const { nodes, materials } = useGLTF("/models/windows.glb");

  const bakedTexture = useTexture("/textures/windows/windows.jpg");
  bakedTexture.flipY = false;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.windows.geometry}
        position={[0.397, 9.122, -11.324]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/windows.glb");
